### PR TITLE
Remove use * for external crates

### LINKED ISSUE #68: intel-mkl-tool: Compilation problem with anyhow 1.0.49
Following the release of anyhow 1.0.49, I get the following compilation error:
<pre>  
...
   Compiling ndarray-linalg v0.14.1
   Compiling zstd v0.5.4+zstd.1.4.7
   Compiling intel-mkl-tool v0.2.0+mkl2020.1
error[E0532]: expected tuple struct or tuple variant, found function `Ok`
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/intel-mkl-tool-0.2.0+mkl2020.1/src/entry.rs:75:16
   |
75 |         if let Ok(dir) = std::env::var("OUT_DIR") {
   |                ^^ not a tuple struct or tuple variant
   |
help: consider importing one of these items instead
   |
1  | use core::result::Result::Ok;
   |
1  | use std::result::Result::Ok;
   |
...
</pre>

It seems like the new `Ok()` function introduced in anyhow breaks the code. see [anyhow 1.0.49 release](https://github.com/dtolnay/anyhow/releases/tag/1.0.49). Pinning anyhow to 1.0.48 solves the problem.
@dtolnay, to also bring this to your attention.

### PR DESCRIPTION
**Pull request by hombit**
Remove wildcard `use` statements from `intel-mkl-tool`, because it
causes problems like #68

Fix #68

### CODE REVIEW

**Comment by hombit** [comment]
Hi @termoshtt, please could you look into this? The issue #68 is really annoying and I see a lot of troubles people have with it

**Comment by jianshu93** [comment]
I have the same build error. How use specify version 1.0.48 for a package depending ton it?

THanks,

Jianshu

**Comment by hombit** [comment]
@jianshu93 This PR resolves the root of the problem, it doesn't pin or limit `anyhow` version of `intel-mkl-tools`. I temporary solved this issue in my project in the same way as others did: just specified `anyhow` version in my `Cargo.toml`:
https://github.com/light-curve/light-curve/commit/15364a8fc1e254f25d1ae82ed33388d4ec290ba5

**Comment by jianshu93** [comment]
Thanks for quick response.

Jianshu

**Comment by adam-azarchs** [comment]
Depending on what features are enabled, this is also an issue in https://github.com/rust-math/intel-mkl-src/blob/84a464e4f32ea658c17e5b4843af64b784abc4d6/intel-mkl-src/build.rs#L25

**Comment by hombit** [comment]
@adam-azarchs this PR was for `intel-mkl-tool` only, but I can do the same for other two crates as well

**Comment by hombit** [comment]
Thank you, @adam-azarchs, I did the same change in `intel-mkl-src/intel-mkl-src/build.rs`

**Comment by njaard** [comment]
@hombit I have forked this crate and applied this patch. https://github.com/njaard/mkl-src/

With appreciation to @termoshtt I'd like to ask you to make further contributions to my fork's repository due to the original author's absence.

**Review by termoshtt — APPROVED** [review]

**Pull request merged**
